# Generated by Django 4.1.3 on 2022-11-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("quoted_by", models.CharField(default="Anonymous", max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="/placeholder.png", null=True, upload_to=""
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "General"),
                            (2, "Love"),
                            (3, "Economy"),
                            (4, "Education"),
                        ],
                        default=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hello", models.CharField(max_length=100)),
            ],
        ),
    ]
