# Generated by Django 4.1.3 on 2022-11-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_quote_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="image",
            field=models.ImageField(
                blank=True, default="anonymous.jpeg", null=True, upload_to=""
            ),
        ),
    ]
