# Generated by Django 4.1.3 on 2022-11-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0004_alter_quote_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="image",
            field=models.ImageField(
                blank=True, default="/anonymous.jpeg", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="type",
            field=models.SmallIntegerField(
                choices=[
                    ("General", "General"),
                    ("Love", "Love"),
                    ("Economy", "Economy"),
                    ("Education", "Education"),
                ],
                default="General",
            ),
        ),
    ]
