# Generated by Django 4.1.3 on 2022-11-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0005_alter_quote_image_alter_quote_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="type",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("Love", "Love"),
                    ("Economy", "Economy"),
                    ("Education", "Education"),
                ],
                default="General",
                max_length=50,
            ),
        ),
    ]
